services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: todo
    ports:
      - "15432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
  app:
    image: ghcr.io/humphreykwok/simple-todo-next:latest
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_URL=postgresql://postgres:test@db:5432/todo
    depends_on:
      - db
    restart: always

volumes:
  postgres-data:
