apiVersion: v1
kind: Service
metadata:
  name: todo-next-service
  labels:
    name: todo-next
    app: todo
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
  selector:
    name: todo-next
    app: todo
